//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitOfWork.Repository.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Racun
    {
        public int Id { get; set; }
        public string Ime { get; set; }
        public decimal StanjeRacuna { get; set; }
    }
}
